# Generated by Django 2.2.4 on 2020-04-07 11:12

from django.db import migrations
from phonenumbers import parse, format_number
from phonenumbers import PhoneNumberFormat, is_valid_number


def convert_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        number = flat.owners_phonenumber
        parsed_number = parse(number, 'RU')
        
        if not is_valid_number(parsed_number):
            continue

        formatted_number = format_number(parsed_number, PhoneNumberFormat.E164)
        flat.owner_phone_pure = formatted_number
        flat.save()
            

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20200407_1411'),
    ]

    operations = [
        migrations.RunPython(convert_phonenumbers)
    ]
