# Generated by Django 2.2.4 on 2020-04-08 16:29

from django.db import migrations

def move_owner_data(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    owners = apps.get_model('property', 'Owner')
    for flat in flats.objects.all():
        owners.objects.get_or_create(
            owner=flat.owner,
            owner_phone_pure=flat.owner_phone_pure,
            owners_phonenumber=flat.owners_phonenumber
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_owner'),
    ]

    operations = [
        migrations.RunPython(move_owner_data)
    ]
