# Generated by Django 2.2.4 on 2020-04-11 12:23

from django.db import migrations

def add_relations_between_flats_and_owners(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    owners = apps.get_model('property', 'Owner')
    for flat in flats.objects.all():
        owner, _ = owners.objects.get_or_create(
            owner=flat.owner,
            owner_phone_pure=flat.owner_phone_pure,
            owners_phonenumber=flat.owners_phonenumber
        )
        owner.flats.add(flat)
        flat.owners.add(owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20200411_1514'),
    ]

    operations = [
        migrations.RunPython(add_relations_between_flats_and_owners)
    ]